on:
  push:
    branches:
      - 'main'

# Declare default permissions as read only.
permissions: read-all

jobs:
  mirror_job:
    permissions:
        contents: write
        deployments: write
    runs-on: ubuntu-latest
    name: Mirror SOURCE_BRANCH_NAME branch to DESTINATION_BRANCH_NAME branch
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@30c52ee21f5d3bd7fb28b95501c11aae7f17eebb # v2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'main'
        dest: 'master'
